package com.sddz.gasstation.entity.PC;

import java.util.Date;

public class AdminSysDictionary {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_sys_dictionary.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_sys_dictionary.dict_type
     *
     * @mbg.generated
     */
    private String dictType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_sys_dictionary.dict_code
     *
     * @mbg.generated
     */
    private String dictCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_sys_dictionary.dict_name
     *
     * @mbg.generated
     */
    private String dictName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_sys_dictionary.dict_description
     *
     * @mbg.generated
     */
    private String dictDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_sys_dictionary.is_sys
     *
     * @mbg.generated
     */
    private String isSys;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_sys_dictionary.seq
     *
     * @mbg.generated
     */
    private Integer seq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_sys_dictionary.ext1
     *
     * @mbg.generated
     */
    private String ext1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_sys_dictionary.ext2
     *
     * @mbg.generated
     */
    private String ext2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_sys_dictionary.ext3
     *
     * @mbg.generated
     */
    private String ext3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_sys_dictionary.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_sys_dictionary.creator
     *
     * @mbg.generated
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_sys_dictionary.modify_time
     *
     * @mbg.generated
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_sys_dictionary.modifyor
     *
     * @mbg.generated
     */
    private String modifyor;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_sys_dictionary
     *
     * @mbg.generated
     */
    public AdminSysDictionary(Long id, String dictType, String dictCode, String dictName, String dictDescription, String isSys, Integer seq, String ext1, String ext2, String ext3, Date createTime, String creator, Date modifyTime, String modifyor) {
        this.id = id;
        this.dictType = dictType;
        this.dictCode = dictCode;
        this.dictName = dictName;
        this.dictDescription = dictDescription;
        this.isSys = isSys;
        this.seq = seq;
        this.ext1 = ext1;
        this.ext2 = ext2;
        this.ext3 = ext3;
        this.createTime = createTime;
        this.creator = creator;
        this.modifyTime = modifyTime;
        this.modifyor = modifyor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_sys_dictionary
     *
     * @mbg.generated
     */
    public AdminSysDictionary() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_sys_dictionary.id
     *
     * @return the value of admin_sys_dictionary.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_sys_dictionary.id
     *
     * @param id the value for admin_sys_dictionary.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_sys_dictionary.dict_type
     *
     * @return the value of admin_sys_dictionary.dict_type
     *
     * @mbg.generated
     */
    public String getDictType() {
        return dictType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_sys_dictionary.dict_type
     *
     * @param dictType the value for admin_sys_dictionary.dict_type
     *
     * @mbg.generated
     */
    public void setDictType(String dictType) {
        this.dictType = dictType == null ? null : dictType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_sys_dictionary.dict_code
     *
     * @return the value of admin_sys_dictionary.dict_code
     *
     * @mbg.generated
     */
    public String getDictCode() {
        return dictCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_sys_dictionary.dict_code
     *
     * @param dictCode the value for admin_sys_dictionary.dict_code
     *
     * @mbg.generated
     */
    public void setDictCode(String dictCode) {
        this.dictCode = dictCode == null ? null : dictCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_sys_dictionary.dict_name
     *
     * @return the value of admin_sys_dictionary.dict_name
     *
     * @mbg.generated
     */
    public String getDictName() {
        return dictName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_sys_dictionary.dict_name
     *
     * @param dictName the value for admin_sys_dictionary.dict_name
     *
     * @mbg.generated
     */
    public void setDictName(String dictName) {
        this.dictName = dictName == null ? null : dictName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_sys_dictionary.dict_description
     *
     * @return the value of admin_sys_dictionary.dict_description
     *
     * @mbg.generated
     */
    public String getDictDescription() {
        return dictDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_sys_dictionary.dict_description
     *
     * @param dictDescription the value for admin_sys_dictionary.dict_description
     *
     * @mbg.generated
     */
    public void setDictDescription(String dictDescription) {
        this.dictDescription = dictDescription == null ? null : dictDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_sys_dictionary.is_sys
     *
     * @return the value of admin_sys_dictionary.is_sys
     *
     * @mbg.generated
     */
    public String getIsSys() {
        return isSys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_sys_dictionary.is_sys
     *
     * @param isSys the value for admin_sys_dictionary.is_sys
     *
     * @mbg.generated
     */
    public void setIsSys(String isSys) {
        this.isSys = isSys == null ? null : isSys.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_sys_dictionary.seq
     *
     * @return the value of admin_sys_dictionary.seq
     *
     * @mbg.generated
     */
    public Integer getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_sys_dictionary.seq
     *
     * @param seq the value for admin_sys_dictionary.seq
     *
     * @mbg.generated
     */
    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_sys_dictionary.ext1
     *
     * @return the value of admin_sys_dictionary.ext1
     *
     * @mbg.generated
     */
    public String getExt1() {
        return ext1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_sys_dictionary.ext1
     *
     * @param ext1 the value for admin_sys_dictionary.ext1
     *
     * @mbg.generated
     */
    public void setExt1(String ext1) {
        this.ext1 = ext1 == null ? null : ext1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_sys_dictionary.ext2
     *
     * @return the value of admin_sys_dictionary.ext2
     *
     * @mbg.generated
     */
    public String getExt2() {
        return ext2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_sys_dictionary.ext2
     *
     * @param ext2 the value for admin_sys_dictionary.ext2
     *
     * @mbg.generated
     */
    public void setExt2(String ext2) {
        this.ext2 = ext2 == null ? null : ext2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_sys_dictionary.ext3
     *
     * @return the value of admin_sys_dictionary.ext3
     *
     * @mbg.generated
     */
    public String getExt3() {
        return ext3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_sys_dictionary.ext3
     *
     * @param ext3 the value for admin_sys_dictionary.ext3
     *
     * @mbg.generated
     */
    public void setExt3(String ext3) {
        this.ext3 = ext3 == null ? null : ext3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_sys_dictionary.create_time
     *
     * @return the value of admin_sys_dictionary.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_sys_dictionary.create_time
     *
     * @param createTime the value for admin_sys_dictionary.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_sys_dictionary.creator
     *
     * @return the value of admin_sys_dictionary.creator
     *
     * @mbg.generated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_sys_dictionary.creator
     *
     * @param creator the value for admin_sys_dictionary.creator
     *
     * @mbg.generated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_sys_dictionary.modify_time
     *
     * @return the value of admin_sys_dictionary.modify_time
     *
     * @mbg.generated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_sys_dictionary.modify_time
     *
     * @param modifyTime the value for admin_sys_dictionary.modify_time
     *
     * @mbg.generated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_sys_dictionary.modifyor
     *
     * @return the value of admin_sys_dictionary.modifyor
     *
     * @mbg.generated
     */
    public String getModifyor() {
        return modifyor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_sys_dictionary.modifyor
     *
     * @param modifyor the value for admin_sys_dictionary.modifyor
     *
     * @mbg.generated
     */
    public void setModifyor(String modifyor) {
        this.modifyor = modifyor == null ? null : modifyor.trim();
    }
}