package com.sddz.gasstation.entity.PC;

import java.math.BigDecimal;
import java.util.Date;

public class GasOrders {

    private Long id;

    private String orderNo;

    private Long userId;

    private Long gasGoodsId;

    private String plateNumber;

    private Long stationId;

    private Long gunId;

    private BigDecimal quantity;

    private BigDecimal price;

    private BigDecimal totalAmount;

    private BigDecimal payAmount;

    private Byte payType;

    private Date createTime;

    private Date payTime;

    private String cardNo;

    public GasOrders(Long id, String orderNo, Long userId, Long gasGoodsId, String plateNumber, Long stationId, Long gunId, BigDecimal quantity, BigDecimal price, BigDecimal totalAmount, BigDecimal payAmount, Byte payType, Date createTime, Date payTime, String cardNo) {
        this.id = id;
        this.orderNo = orderNo;
        this.userId = userId;
        this.gasGoodsId = gasGoodsId;
        this.plateNumber = plateNumber;
        this.stationId = stationId;
        this.gunId = gunId;
        this.quantity = quantity;
        this.price = price;
        this.totalAmount = totalAmount;
        this.payAmount = payAmount;
        this.payType = payType;
        this.createTime = createTime;
        this.payTime = payTime;
        this.cardNo = cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gas_orders
     *
     * @mbg.generated
     */
    public GasOrders() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gas_orders.id
     *
     * @return the value of gas_orders.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gas_orders.id
     *
     * @param id the value for gas_orders.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gas_orders.order_no
     *
     * @return the value of gas_orders.order_no
     *
     * @mbg.generated
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gas_orders.order_no
     *
     * @param orderNo the value for gas_orders.order_no
     *
     * @mbg.generated
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gas_orders.user_id
     *
     * @return the value of gas_orders.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gas_orders.user_id
     *
     * @param userId the value for gas_orders.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gas_orders.gas_goods_id
     *
     * @return the value of gas_orders.gas_goods_id
     *
     * @mbg.generated
     */
    public Long getGasGoodsId() {
        return gasGoodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gas_orders.gas_goods_id
     *
     * @param gasGoodsId the value for gas_orders.gas_goods_id
     *
     * @mbg.generated
     */
    public void setGasGoodsId(Long gasGoodsId) {
        this.gasGoodsId = gasGoodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gas_orders.plate_number
     *
     * @return the value of gas_orders.plate_number
     *
     * @mbg.generated
     */
    public String getPlateNumber() {
        return plateNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gas_orders.plate_number
     *
     * @param plateNumber the value for gas_orders.plate_number
     *
     * @mbg.generated
     */
    public void setPlateNumber(String plateNumber) {
        this.plateNumber = plateNumber == null ? null : plateNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gas_orders.station_id
     *
     * @return the value of gas_orders.station_id
     *
     * @mbg.generated
     */
    public Long getStationId() {
        return stationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gas_orders.station_id
     *
     * @param stationId the value for gas_orders.station_id
     *
     * @mbg.generated
     */
    public void setStationId(Long stationId) {
        this.stationId = stationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gas_orders.gun_id
     *
     * @return the value of gas_orders.gun_id
     *
     * @mbg.generated
     */
    public Long getGunId() {
        return gunId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gas_orders.gun_id
     *
     * @param gunId the value for gas_orders.gun_id
     *
     * @mbg.generated
     */
    public void setGunId(Long gunId) {
        this.gunId = gunId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gas_orders.quantity
     *
     * @return the value of gas_orders.quantity
     *
     * @mbg.generated
     */
    public BigDecimal getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gas_orders.quantity
     *
     * @param quantity the value for gas_orders.quantity
     *
     * @mbg.generated
     */
    public void setQuantity(BigDecimal quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gas_orders.price
     *
     * @return the value of gas_orders.price
     *
     * @mbg.generated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gas_orders.price
     *
     * @param price the value for gas_orders.price
     *
     * @mbg.generated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gas_orders.total_amount
     *
     * @return the value of gas_orders.total_amount
     *
     * @mbg.generated
     */
    public BigDecimal getTotalAmount() {
        return totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gas_orders.total_amount
     *
     * @param totalAmount the value for gas_orders.total_amount
     *
     * @mbg.generated
     */
    public void setTotalAmount(BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gas_orders.pay_amount
     *
     * @return the value of gas_orders.pay_amount
     *
     * @mbg.generated
     */
    public BigDecimal getPayAmount() {
        return payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gas_orders.pay_amount
     *
     * @param payAmount the value for gas_orders.pay_amount
     *
     * @mbg.generated
     */
    public void setPayAmount(BigDecimal payAmount) {
        this.payAmount = payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gas_orders.pay_type
     *
     * @return the value of gas_orders.pay_type
     *
     * @mbg.generated
     */
    public Byte getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gas_orders.pay_type
     *
     * @param payType the value for gas_orders.pay_type
     *
     * @mbg.generated
     */
    public void setPayType(Byte payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gas_orders.create_time
     *
     * @return the value of gas_orders.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gas_orders.create_time
     *
     * @param createTime the value for gas_orders.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gas_orders.pay_time
     *
     * @return the value of gas_orders.pay_time
     *
     * @mbg.generated
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gas_orders.pay_time
     *
     * @param payTime the value for gas_orders.pay_time
     *
     * @mbg.generated
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gas_orders.card_no
     *
     * @return the value of gas_orders.card_no
     *
     * @mbg.generated
     */
    public String getCardNo() {
        return cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gas_orders.card_no
     *
     * @param cardNo the value for gas_orders.card_no
     *
     * @mbg.generated
     */
    public void setCardNo(String cardNo) {
        this.cardNo = cardNo == null ? null : cardNo.trim();
    }
}
