package com.sddz.gasstation.entity.PC;

import java.util.Date;

public class GasWxMp {

    private Long id;

    private String mpName;

    private String appId;

    private String appSecret;

    private String orderAcceptTemplateId;

    private String paySuccessTemplateId;

    private String authUrl;

    private Date createTime;

    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gas_wx_mp.creator
     *
     * @mbg.generated
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gas_wx_mp.modifier
     *
     * @mbg.generated
     */
    private String modifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gas_wx_mp.token
     *
     * @mbg.generated
     */
    private String token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gas_wx_mp.encoding_aes_key
     *
     * @mbg.generated
     */
    private String encodingAesKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gas_wx_mp.subscribe_reply
     *
     * @mbg.generated
     */
    private String subscribeReply;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gas_wx_mp.car_come_template_id
     *
     * @mbg.generated
     */
    private String carComeTemplateId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gas_wx_mp
     *
     * @mbg.generated
     */
    public GasWxMp(Long id, String mpName, String appId, String appSecret, String orderAcceptTemplateId, String paySuccessTemplateId, String authUrl, Date createTime, Date modifyTime, String creator, String modifier, String token, String encodingAesKey, String subscribeReply, String carComeTemplateId) {
        this.id = id;
        this.mpName = mpName;
        this.appId = appId;
        this.appSecret = appSecret;
        this.orderAcceptTemplateId = orderAcceptTemplateId;
        this.paySuccessTemplateId = paySuccessTemplateId;
        this.authUrl = authUrl;
        this.createTime = createTime;
        this.modifyTime = modifyTime;
        this.creator = creator;
        this.modifier = modifier;
        this.token = token;
        this.encodingAesKey = encodingAesKey;
        this.subscribeReply = subscribeReply;
        this.carComeTemplateId = carComeTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gas_wx_mp
     *
     * @mbg.generated
     */
    public GasWxMp() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gas_wx_mp.id
     *
     * @return the value of gas_wx_mp.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gas_wx_mp.id
     *
     * @param id the value for gas_wx_mp.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gas_wx_mp.mp_name
     *
     * @return the value of gas_wx_mp.mp_name
     *
     * @mbg.generated
     */
    public String getMpName() {
        return mpName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gas_wx_mp.mp_name
     *
     * @param mpName the value for gas_wx_mp.mp_name
     *
     * @mbg.generated
     */
    public void setMpName(String mpName) {
        this.mpName = mpName == null ? null : mpName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gas_wx_mp.app_id
     *
     * @return the value of gas_wx_mp.app_id
     *
     * @mbg.generated
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gas_wx_mp.app_id
     *
     * @param appId the value for gas_wx_mp.app_id
     *
     * @mbg.generated
     */
    public void setAppId(String appId) {
        this.appId = appId == null ? null : appId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gas_wx_mp.app_secret
     *
     * @return the value of gas_wx_mp.app_secret
     *
     * @mbg.generated
     */
    public String getAppSecret() {
        return appSecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gas_wx_mp.app_secret
     *
     * @param appSecret the value for gas_wx_mp.app_secret
     *
     * @mbg.generated
     */
    public void setAppSecret(String appSecret) {
        this.appSecret = appSecret == null ? null : appSecret.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gas_wx_mp.order_accept_template_id
     *
     * @return the value of gas_wx_mp.order_accept_template_id
     *
     * @mbg.generated
     */
    public String getOrderAcceptTemplateId() {
        return orderAcceptTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gas_wx_mp.order_accept_template_id
     *
     * @param orderAcceptTemplateId the value for gas_wx_mp.order_accept_template_id
     *
     * @mbg.generated
     */
    public void setOrderAcceptTemplateId(String orderAcceptTemplateId) {
        this.orderAcceptTemplateId = orderAcceptTemplateId == null ? null : orderAcceptTemplateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gas_wx_mp.pay_success_template_id
     *
     * @return the value of gas_wx_mp.pay_success_template_id
     *
     * @mbg.generated
     */
    public String getPaySuccessTemplateId() {
        return paySuccessTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gas_wx_mp.pay_success_template_id
     *
     * @param paySuccessTemplateId the value for gas_wx_mp.pay_success_template_id
     *
     * @mbg.generated
     */
    public void setPaySuccessTemplateId(String paySuccessTemplateId) {
        this.paySuccessTemplateId = paySuccessTemplateId == null ? null : paySuccessTemplateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gas_wx_mp.auth_url
     *
     * @return the value of gas_wx_mp.auth_url
     *
     * @mbg.generated
     */
    public String getAuthUrl() {
        return authUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gas_wx_mp.auth_url
     *
     * @param authUrl the value for gas_wx_mp.auth_url
     *
     * @mbg.generated
     */
    public void setAuthUrl(String authUrl) {
        this.authUrl = authUrl == null ? null : authUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gas_wx_mp.create_time
     *
     * @return the value of gas_wx_mp.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gas_wx_mp.create_time
     *
     * @param createTime the value for gas_wx_mp.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gas_wx_mp.modify_time
     *
     * @return the value of gas_wx_mp.modify_time
     *
     * @mbg.generated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gas_wx_mp.modify_time
     *
     * @param modifyTime the value for gas_wx_mp.modify_time
     *
     * @mbg.generated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gas_wx_mp.creator
     *
     * @return the value of gas_wx_mp.creator
     *
     * @mbg.generated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gas_wx_mp.creator
     *
     * @param creator the value for gas_wx_mp.creator
     *
     * @mbg.generated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gas_wx_mp.modifier
     *
     * @return the value of gas_wx_mp.modifier
     *
     * @mbg.generated
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gas_wx_mp.modifier
     *
     * @param modifier the value for gas_wx_mp.modifier
     *
     * @mbg.generated
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gas_wx_mp.token
     *
     * @return the value of gas_wx_mp.token
     *
     * @mbg.generated
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gas_wx_mp.token
     *
     * @param token the value for gas_wx_mp.token
     *
     * @mbg.generated
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gas_wx_mp.encoding_aes_key
     *
     * @return the value of gas_wx_mp.encoding_aes_key
     *
     * @mbg.generated
     */
    public String getEncodingAesKey() {
        return encodingAesKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gas_wx_mp.encoding_aes_key
     *
     * @param encodingAesKey the value for gas_wx_mp.encoding_aes_key
     *
     * @mbg.generated
     */
    public void setEncodingAesKey(String encodingAesKey) {
        this.encodingAesKey = encodingAesKey == null ? null : encodingAesKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gas_wx_mp.subscribe_reply
     *
     * @return the value of gas_wx_mp.subscribe_reply
     *
     * @mbg.generated
     */
    public String getSubscribeReply() {
        return subscribeReply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gas_wx_mp.subscribe_reply
     *
     * @param subscribeReply the value for gas_wx_mp.subscribe_reply
     *
     * @mbg.generated
     */
    public void setSubscribeReply(String subscribeReply) {
        this.subscribeReply = subscribeReply == null ? null : subscribeReply.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gas_wx_mp.car_come_template_id
     *
     * @return the value of gas_wx_mp.car_come_template_id
     *
     * @mbg.generated
     */
    public String getCarComeTemplateId() {
        return carComeTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gas_wx_mp.car_come_template_id
     *
     * @param carComeTemplateId the value for gas_wx_mp.car_come_template_id
     *
     * @mbg.generated
     */
    public void setCarComeTemplateId(String carComeTemplateId) {
        this.carComeTemplateId = carComeTemplateId == null ? null : carComeTemplateId.trim();
    }
}
