package com.sddz.gasstation.dao.mapper;

import com.sddz.gasstation.entity.PC.AdminSysDictionary;
import com.sddz.gasstation.param.SysDictionaryParam;

import java.util.List;

public interface AdminSysDictionaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_sys_dictionary
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_sys_dictionary
     *
     * @mbg.generated
     */
    int insert(AdminSysDictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_sys_dictionary
     *
     * @mbg.generated
     */
    int insertSelective(AdminSysDictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_sys_dictionary
     *
     * @mbg.generated
     */
    AdminSysDictionary selectByPrimaryKey(Long id);
    List<AdminSysDictionary> selectByDicType(String dicType);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_sys_dictionary
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AdminSysDictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_sys_dictionary
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AdminSysDictionary record);

    List<AdminSysDictionary> selectByDicTypeParam(SysDictionaryParam param);
}
